name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: install deps
      run: |
        python3 -m pip install python-debianbts unidecode
    - name: smoke test
      run: |
        ./freshbugs 123456 654321 nobody@example.org
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
